# Makefile

include ../../../configure.make

MODEL = idct2d_test.xml


include $(SBROOT)/dev/source/make/smoc.make
include $(SBROOT)/dev/source/make/test.make
include $(SBROOT)/dev/source/make/general.make


