/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class systemoc_plugin_jni_SysteMoC */

#ifndef _Included_systemoc_plugin_jni_SysteMoC
#define _Included_systemoc_plugin_jni_SysteMoC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     systemoc_plugin_jni_SysteMoC
 * Method:    runSimulation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_systemoc_plugin_jni_SysteMoC_runSimulation
  (JNIEnv *, jobject);

/*
 * Class:     systemoc_plugin_jni_SysteMoC
 * Method:    runSimulationWithStringParams
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_systemoc_plugin_jni_SysteMoC_runSimulationWithStringParams
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     systemoc_plugin_jni_SysteMoC
 * Method:    startSimulation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_systemoc_plugin_jni_SysteMoC_startSimulation
  (JNIEnv *, jobject);

/*
 * Class:     systemoc_plugin_jni_SysteMoC
 * Method:    stopSimulation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_systemoc_plugin_jni_SysteMoC_stopSimulation
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
